name: Go

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BINARY_NAME: "checker"
      VERSION: ${GITHUB_REF##*/}

    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: go build -v -i -ldflags "-X my/checker/config.Version=${VERSION} -X my/checker/config.VersionSHA=${GITHUB_SHA} -X my/checker/config.VersionBuild=${GITHUB_RUN_ID}" -o build/${BINARY_NAME}

      - name: Compress binary
        run: tar -czvf ${BINARY_NAME}-${VERSION}-linux-amd64.tgz build/${BINARY_NAME}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: checker
          path: ${{ env.BINARY_NAME }}-${{ env.VERSION }}-linux-amd64.tgz

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          repository: ${{ secrets.REGISTRY_LOGIN }}/checker
          tag_with_ref: true
          tag_with_sha: true
